Solve_Internship/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(('app1.urls','app1'),namespace='app1')), #use of namespace for the dynamic url call in web_scrape.html action
]

app1/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    path('',views.indexView, name='home'),
    path('register',views.register,name='register_url'),
    path('login',LoginView.as_view(),name="login_url"),
    path('logout',LogoutView.as_view(next_page='app1:login_url'),name="logout"),
    path("home",views.index1,name="index1"),
    path("emails_text",views.emails_text,name="emails_txt"),
    # path("analyze",views.analyze,name="analyze_text"),
    path("phone_number_text",views.phone_numbers_text,name='phone_text'),
    path("url_text",views.url_text,name="text_url"),
    # path("web_scrape",views.web_scrape,name="web_scrape"),
    path("download_pdf",views.download_pdf,name="pdf"),
    path("download_pdf_result",views.download_pdf_result,name="download_pdf_res"),
    path("url_scrape",views.url_scrape,name="scrape_url"),
    path("url_scraping_result",views.url_scraping_result,name="scrape_url_res"),
    path('email_scrape',views.emails_scrape,name="scrape_email"),
    path("email_scraping_result",views.emails_scraping_result,name="scrape_email_res"),
    path("phone_number_scrape",views.phone_number_scrape,name="phone_number"),
    path("phone_number_scrape_result",views.phoneNumber_scraping_result,name="phone_scrape_res"),
    path("google_maps",views.google_maps,name="gmaps"),
    path("gmaps_redirect",views.google_maps_redirect,name="gmaps_redirect"),
    path("youtube_download",views.youtube_download,name="ytube"),
    path("youtube_download_res",views.youtube_download_res,name="ytube_res"),
    path("upload_audio",views.upload_audio,name="audio"),
    path('audio_text',views.audio_text,name='audio_txt'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models

class Download(models.Model):
    download_id=models.AutoField

app1/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
import re
import requests
from bs4 import BeautifulSoup
import os
from selenium import webdriver
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import os
import csv
import youtube_dl
import speech_recognition as sr
from os import path
from pydub import AudioSegment
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
def indexView(request):
    return render(request,"index.html")
# @login_required
def register(request):
    if request.method=="POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login_url')
    else:
        form=UserCreationForm()
    return render(request,'registration/register.html',{'form':form})

def index1(request):
    return render(request, 'app1/index1.html')

def emails_text(request):
    return render(request,'app1/emails_text _1.html')

def phone_numbers_text(request):
    return render(request,'app1/phone_number_text.html')

def url_text(request):
    return render(request,'app1/url_text.html')

# def analyze(request):
#     text=request.POST.get("text")
#     check1=request.POST.get('extract_emails',"off")
#     check2=request.POST.get('extract_phone_no.',"off")
#     check3 = request.POST.get('extract_urls.', "off")
#     if check2=='on':
#         phone_number=re.findall('[0-9]+',text)
#         param={'res':phone_number}
#         return render(request,'app1/analyze.html',param)
#     elif check1=='on':
#         emails=re.findall('\S+@\S+',text)
#         param={'res':emails}
#         return render(request,'app1/analyze.html',param)
#     else:
#         url = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]| [! * \(\),] | (?: %[0-9a-fA-F][0-9a-fA-F]))+',text)
#         print(url)
#         param={'res':url}
#         return render(request,'app1/analyze.html',param)

def web_scrape(request):
    s = "<button type='button'> <a href = 'http://127.0.0.1:8000/url_scraping'>Extract URLs from the link</a></button> <br> " \
        "<button type='button'> <a href = 'http://127.0.0.1:8000/download_pdf'>Download PDF from the URL</a></button>"
    return HttpResponse(s)
    # return render(request,"app1/web_scrape.html")

def download_pdf(request):
    return render(request,"app1/download_pdf.html")
def download_pdf_result(request):
    if request.method=="POST":
        # urls = ['http://www.edudel.nic.in/welcome_folder/SupportMaterial2019_20/IX/English/9_sm_maths_eng_2019_20.pdf']
        text_urls=request.POST.get("txt1")
        print(text_urls)
        # print(type(text_urls))
        # urls=list(text_urls)
        # print(urls)
        # print(type(urls))
        name=text_urls.split('/')[-1]
        print(name)
        myfile = requests.get(text_urls, allow_redirects=True,stream=True)
        with open(name, 'wb')as pdf:
            for chunk in myfile.iter_content(chunk_size=1024):
                if chunk:
                    pdf.write(chunk)

        return HttpResponse("Your PDF is downloaded")

def url_scrape(request):
    return render(request,"app1/url_scrape.html")
def url_scraping_result(request):
    # text=request.POST.get('text')
    # url = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]| [! * \(\),] | (?: %[0-9a-fA-F][0-9a-fA-F]))+', text)
    # first_url=url[0]
    if request.method=="POST":
        # first_url="https://www.aldaily.com"
        first_url=request.POST.get("txt1")
        r=requests.get(first_url)
        htmlcontent=r.content
        # print(htmlcontent)
        soup=BeautifulSoup(htmlcontent,'html.parser')
        links=[]
        for link in soup.find_all('a'):
            links.append(link.get('href'))
            # print("coming links",links)
        # print("final links",links)
        param={'res':links}
        return render(request, 'app1/url_scrape_result.html', param)

def emails_scrape(request):
    return render(request,"app1/email_scrape.html")
def emails_scraping_result(request):
    if request.method=="POST":
        url=request.POST.get('txt1')
        # first_url = "https://www.aldaily.com"
        r=requests.get(url)
        htmlcontent=r.content
        soup=BeautifulSoup(htmlcontent,"html.parser")
        myfile=open("1.txt","w",encoding='utf-8')
        myfile.write(str(soup))
        myfile.close()
        myfile=open("1.txt","r",encoding='utf=8')
        content=myfile.read()
        myfile.close()
        os.remove("1.txt")
        emails = re.findall('\S+@\S+', content)
        # print(emails)
        param = {'res': emails}
        return render(request, 'app1/email_scrape_result.html', param)

def phone_number_scrape(request):
    return render(request,'app1/phone_number_scrape.html')
def phoneNumber_scraping_result(request):
    if request.method=='POST':
        # url = 'https://www.aldaily.com'
        url=request.POST.get("txt1")
        r = requests.get(url)
        htmlcontent = r.content
        soup = BeautifulSoup(htmlcontent,"html.parser")
        myfile = open("1.txt", "w", encoding='utf-8')
        myfile.write(str(soup))
        myfile.close()
        myfile = open("1.txt", "r", encoding='utf=8')
        content = myfile.read()
        myfile.close()
        os.remove("1.txt")
        phone_number = re.findall('[0-9]+', content)
        param = {'res': phone_number}
        return render(request, 'app1/phone_number_scrape_result.html', param)

def google_maps(request):
    return render(request,"app1/gmaps.html")

def google_maps_redirect(request):
    if request.method=="POST":
        text=request.POST.get('text')
        print(text)
        queries=list(text.split('\r\n'))
        print(queries)
        browser = webdriver.Chrome("C:/Users/Divij/Downloads/chromedriver.exe")
        browser.get("https://www.google.com/maps/")
        for i in queries:
            filename=i
            search = browser.find_element_by_id("searchboxinput")
            search.send_keys(i)
            time.sleep(2)
            click_me = browser.find_element_by_id("searchbox-searchbutton")
            click_me.click()
            time.sleep(4)
            fn = open(filename + '.csv', mode='a', encoding="utf-8")
            write_outfile = csv.writer(fn)
            next_page = browser.find_element_by_class_name("n7lv7yjyC35__button-next-icon")
            count = 0
            while True:
                click_me = browser.find_elements_by_xpath("//h3[@class='section-result-title']")
                print(len(click_me))
                click_me1 = click_me
                for i in range(0, len(click_me1)):
                    count = count + 1
                    time.sleep(2)
                    click_me[i].click()
                    time.sleep(2)
                    Name = browser.find_elements_by_xpath('//*[@id="pane"]/div/div[1]/div/div/div[2]/div[1]/div[1]/h1')
                    Address = browser.find_elements_by_xpath("(//span[@class='widget-pane-link'])[3]")
                    Number = browser.find_elements_by_xpath("(//span[@class='widget-pane-link'])[5]")
                    Website = browser.find_elements_by_xpath("(//span[@class='widget-pane-link'])[6]")
                    if len(Address) > 0 and len(Number) > 0 and len(Website) > 0 and len(Name) > 0:
                        Name = browser.find_element_by_xpath(
                            '//*[@id="pane"]/div/div[1]/div/div/div[2]/div[1]/div[1]/h1').text
                        Address = browser.find_element_by_xpath("(//span[@class='widget-pane-link'])[3]").text
                        Number = browser.find_element_by_xpath("(//span[@class='widget-pane-link'])[5]").text
                        Website = browser.find_element_by_xpath("(//span[@class='widget-pane-link'])[6]").text
                        # print(Name,Number,Address,Website)
                        write_outfile.writerow([Name, Number, Address, Website])
                        print("done")
                    time.sleep(2)
                    browser.find_element_by_xpath("//*[text()='Back to results']").click()
                    time.sleep(2)
                    click_me = browser.find_elements_by_xpath("//h3[@class='section-result-title']")
                    print(len(click_me))
                    time.sleep(2)
                next_page = browser.find_element_by_class_name("n7lv7yjyC35__button-next-icon")
                if next_page.is_enabled() and count < 20:
                    next_page.click()
                else:
                    break
            search.clear()
        print('finished')
    return HttpResponse("welcome to google maps redirect")

def youtube_download(request):
    return render(request,"app1/youtube_download.html")
ydl_opts1 = {}
ydl_opts2 = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav',
        'preferredquality': '192',
    }],
}

def youtube_download_res(request):
    if request.method=="POST":
        if request.POST.get('yVideo'):
            link=request.POST.get('yVideo')
            print(link)
            zxt=link.strip()

            with youtube_dl.YoutubeDL(ydl_opts1) as ydl:
                ydl.download([zxt])
            return HttpResponse("Download complete")
        else:
            link=request.POST.get('yAudio')
            print(link)
            zxt=link.strip()

            with youtube_dl.YoutubeDL(ydl_opts2) as ydl:
                ydl.download([zxt])
            return HttpResponse("Download complete")

def upload_audio(request):
    return render(request,"app1/upload.html")
def audio_text(request):
    # src = "Convert Audio File to Text in Python - Speech Recognition in Python   KGP Talkie-dIcoMJqWWYA.mp3"
    # dst = "test.wav"
    #

app1/templates/app1/analyze.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Analyze text</title>
    <script>
function myFunction() {
  var copyText = document.getElementById("numbers");
  copyText.select();
  copyText.setSelectionRange(0, 99999)
  document.execCommand("copy");
}
</script>
</head>
<body>
<h1>Analyze Text</h1>
<textarea name="text"  id="numbers" style="margin: 0px; width: 750px; height: 200px;">
    {% for i in res %}
    {{i}}
{% endfor %}
</textarea>
<br>
<button onclick="myFunction()">Copy text</button>

</body>
</html>

app1/templates/app1/audio_text_res.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Audio result</title>
</head>
<body>
<h1> Audio Text</h1>
<textarea value="text1" id="text1" spellcheck="false" style="margin: 0px; width: 732px; height: 133px;">{{ audio_text }}</textarea>
<br>
<button id="btn1" onclick="myFunction()">Copy text</button>
<script>
function myFunction() {
  var copyText = document.getElementById("text1");
  copyText.select();
  copyText.setSelectionRange(0, 99999)
  document.execCommand("copy");
}
</script>
</body>
</html>

app1/templates/app1/email_scrape.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Scrape</title>
</head>
<body>
<h1>Email Scrape from Input Link</h1>
<form method="post" action="{% url 'app1:scrape_email_res' %}">
    {% csrf_token %}
<textarea value="text1" name="txt1"spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>
<button type="submit">Submit</button>
</form>
</body>
</html>

app1/templates/app1/email_scrape_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Scrape Result</title>
</head>
<body>
<h1>Email Scrape Result</h1>
<textarea value="text2" id="text2"name="txt2"spellcheck="false" style="margin: 0px; width: 732px; height: 133px;">
    {% for i in res %}
        {{ i }}
    {% endfor %}
</textarea>
<br>
<button onclick="myFunction()">Copy text</button>
<script>
function myFunction() {
  var copyText = document.getElementById("text2");
  copyText.select();
  copyText.setSelectionRange(0, 99999)
  document.execCommand("copy");
}
</script>
</body>
</html>

app1/templates/app1/emails_text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Emails_Text</title>

</head>
<body>
<h1>Extract Emails from the text</h1>
<form method="post" id="panda">
{% csrf_token %}
<textarea value="text1" id="txt1"spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>
<button type="submit" onclick="display_data()" id="emails_text">Click for Results</button>
<textarea name="text2" id="text2" name="txt2" style="display: none" spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>
<button id="btn1" id="btn1" onclick="myFunction()" style="display: none">Copy text</button>
</form>
<script>
function myFunction() {
  var copyText = document.getElementById("numbers");
  copyText.select();
  copyText.setSelectionRange(0, 99999)
  document.execCommand("copy");
}
function display_data(val) {
    emails = val.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/gi)
    var element1=document.getElementById('txt1').value;
    window.alert(element1)
{#var element2=document.getElementById('btn1');#}
{#element1.style.display = 'block';#}
{#document.getElementById("text2").innerText='emails';#}
{#element2.style.display = 'block';#}
}
var form = document.getElementById("panda");

      // attach event listener
      form.addEventListener("submit", my_func, true);
</script>
</body>
</html>

app1/templates/app1/gmaps.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GMaps</title>
</head>
<body>
<h1> Please enter you query for google maps search</h1>
<form method="post" action="{% url 'app1:gmaps_redirect' %}">
    {% csrf_token %}
    <textarea name="text" spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>
    <br>
    <button type="submit" name="btn" id="btn">Submit</button>
</form>
</body>
</html>

app1/templates/app1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Solve</title>
</head>
<body>
<h1>Choose an option</h1>
<form action="analyze" method="post">
{% csrf_token %}
    <input type=button onClick="location.href='{% url 'app1:emails_txt' %}'" value='Extract Emails from the text'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/emails_text">Extract Emails from the text</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:phone_text' %}'" value='Extract Phone Numbers from text'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/phone_number_text">Extract Phone Numbers from text</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:text_url' %}'" value='Extract Urls from text'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/url_text">Extract Urls from the text</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:scrape_email' %}'" value='Extract Emails from the provided URL by the user'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/email_scrape">Extract Emails from the provided URL by the user</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:phone_number' %}'" value='Extract Phone Numbers from the provided URL by the user'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/phone_number_scrape">Extract Phone Numbers from the provided URL by the user</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:scrape_url' %}'" value='Extract URLS from the provided URL by the user'>
{#    <button type="submit" formaction ="http://127.0.0.1:8000/url_scrape">Extract URLS from the provided URL by the user</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:pdf' %}'" value='Download PDF from the provided link by the user'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/download_pdf">Download PDF from the provided link by the user</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:gmaps' %}'" value='Google Maps data extraction(CSV)'>
    <br>
    <input type=button onClick="location.href='{% url 'app1:ytube' %}'" value='Download Youtube Video'>
    <br>
    <input type=button onClick="location.href='{% url 'app1:audio' %}'" value='Transcript Audio to text'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/google_maps">Google Maps data extraction(CSV)</button>#}
{#    <br>#}
{#    <textarea name="text" spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>#}
{#    <br>#}
{#    <input type="checkbox" name="extract_emails">Extract Emails#}
{#    <br>#}
{#    <input type="checkbox" name="extract_phone_no."> Extract Phone number#}
{#    <br>#}
{#    <input type="checkbox" name="extract_urls"> Extract Urls#}
{#    <br>#}
{#    <button type="submit">Submit</button>#}
{#    <button type="submit" formaction ="http://127.0.0.1:8000/url_scraping">Extract URLS from the Link</button>#}

</form>
</body>
</html>

app1/templates/app1/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Solve</title>
</head>
<body>
<h1>
    Welcome, {{ user.username }}!
</h1>
<h2>Choose an option</h2>
<form action="analyze" method="post">
{% csrf_token %}
    <input type=button onClick="location.href='{% url 'app1:emails_txt' %}'" value='Extract Emails from the text'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/emails_text">Extract Emails from the text</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:phone_text' %}'" value='Extract Phone Numbers from text'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/phone_number_text">Extract Phone Numbers from text</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:text_url' %}'" value='Extract Urls from text'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/url_text">Extract Urls from the text</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:scrape_email' %}'" value='Extract Emails from the provided URL by the user'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/email_scrape">Extract Emails from the provided URL by the user</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:phone_number' %}'" value='Extract Phone Numbers from the provided URL by the user'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/phone_number_scrape">Extract Phone Numbers from the provided URL by the user</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:scrape_url' %}'" value='Extract URLS from the provided URL by the user'>
{#    <button type="submit" formaction ="http://127.0.0.1:8000/url_scrape">Extract URLS from the provided URL by the user</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:pdf' %}'" value='Download PDF from the provided link by the user'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/download_pdf">Download PDF from the provided link by the user</button>#}
    <br>
    <input type=button onClick="location.href='{% url 'app1:gmaps' %}'" value='Google Maps data extraction(CSV)'>
    <br>
    <input type=button onClick="location.href='{% url 'app1:ytube' %}'" value='Download Youtube Video'>
    <br>
    <input type=button onClick="location.href='{% url 'app1:audio' %}'" value='Transcript Audio to text'>
{#    <button type="submit" formaction ="http://utilityintellify.herokuapp.com/google_maps">Google Maps data extraction(CSV)</button>#}
{#    <br>#}
{#    <textarea name="text" spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>#}
{#    <br>#}
{#    <input type="checkbox" name="extract_emails">Extract Emails#}
{#    <br>#}
{#    <input type="checkbox" name="extract_phone_no."> Extract Phone number#}
{#    <br>#}
{#    <input type="checkbox" name="extract_urls"> Extract Urls#}
{#    <br>#}
{#    <button type="submit">Submit</button>#}
{#    <button type="submit" formaction ="http://127.0.0.1:8000/url_scraping">Extract URLS from the Link</button>#}

</form>
</body>
</html>

app1/templates/app1/phone_number_scrape.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phone Number Scrape</title>
</head>
<body>
<h1>Phone Number Scrape from the link</h1>
<form method="post" action="{% url 'app1:phone_scrape_res' %}">
    {% csrf_token %}
<textarea value="text1" name="txt1"spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>
<button type="submit">Submit</button>
</form>
</body>
</html>

app1/templates/app1/phone_number_scrape_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phone Number Scrape Result</title>
</head>
<body>
<h1> Phone Number Scrape Result</h1>
<textarea value="text2" id="text2" name="txt2"spellcheck="false" style="margin: 0px; width: 732px; height: 133px;">
    {% for i in res %}
        {{ i }}
    {% endfor %}
</textarea>
<br>
<button id="btn1"onclick="myFunction()">Copy text</button>
<script>
function myFunction() {
  var copyText = document.getElementById("text2");
  copyText.select();
  copyText.setSelectionRange(0, 99999)
  document.execCommand("copy");
}
</script>
</body>
</html>

app1/templates/app1/phone_number_text.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Emails_Text</title>
  </head>
  <body>
    <h1>Extract Phone Numbers from the text</h1>
    <form id="panda" method="post">
      {% csrf_token %}
      <textarea value="phone_text1" id="phone_text1" spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>
      <button type="submit" id="phone_no">
        Click for Results
      </button>
      <textarea name="phone_text2"  id="phone_text2" name="phone2" style="display: none;" spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"
      ></textarea>
      <button id="btn1" id="btn1" onclick="myFunction()" style="display: none;">Copy text </button>
    </form>
    <script>
      function myFunction() {
        var copyText = document.getElementById("phone_text2");
        copyText.select();
        copyText.setSelectionRange(0, 99999);
        document.execCommand("copy");
      }
      function display_data(val) {
        var element1 = document.getElementById("phone_text1");
        var element3=document.getElementById("btn1")
        let phone_nos = val.match(
          /([0-9]+)/gi
        );
        var element2 = document.getElementById("phone_text2");
        element1.style.display = "block";
        document.getElementById("phone_text2").innerText = phone_nos;
        element2.style.display = "block";
        element3.style.display="block"
      }

      var my_func = function (event) {
        event.preventDefault();
        var element1 = document.getElementById("phone_text1");
        display_data(element1.value);
      };

      var form = document.getElementById("panda");
      form.addEventListener("submit", my_func, true);
    </script>
  </body>
</html>

app1/templates/app1/url_scrape.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Url Scrape</title>
</head>
<body>
<h1>URL Scrape from the link</h1>
<form method="post" action="{% url 'app1:scrape_url_res' %}">
    {% csrf_token %}
<textarea value="text1" name="txt1"spellcheck="false" style="margin: 0px; width: 732px; height: 133px;"></textarea>
<button type="submit">Submit</button>
</form>
</body>
</html>

app1/templates/app1/youtube_download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Youtube Video Download</title>
</head>
<body>
<h1>Input the Youtube link for download</h1>
<form method="post" action={% url 'app1:ytube_res' %} >
    {% csrf_token %}
   <select name="color" onchange='CheckOption(this.value);'>
    <option>Pick an Option</option>
    <option value="yvideo">Download Video</option>
    <option value="yaudio">Download Audio</option>
       <option value="ytext">Transcript Text from Audio/text</option>
  </select>

{#<input type="url" name="goo" id="google" style='display:none;' pattern="https://.*"  placeholder="https://example.com"/>#}
    <textarea type="text" name="yVideo" id="yVideo" style="display:none;margin: 0px; width: 732px; height: 133px;" placeholder="https://youtube.com" size="30"></textarea>
    <textarea type="text"  name="yAudio" id="yAudio" style="display:none;margin: 0px; width: 732px; height: 133px;" placeholder="https://youtube.com/abcd.pdf" size="30"></textarea>
    <textarea type="text"  name="yText" id="yText" style="display:none;margin: 0px; width: 732px; height: 133px;" placeholder="https://youtube.com/abcd.pdf" size="30"></textarea>
<br>
    <button type="submit"> Submit</button>
</form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script type="text/javascript">
             function CheckOption(val){
            var element=document.getElementById('yVideo');
            var element1=document.getElementById('yAudio');
            var element2=document.getElementById('yText')
            if(val=='yvideo') {
                element.style.display = 'block';
                element1.style.display = 'none';
                element2.style.display = 'none';
            }
            else if(val=='yaudio'){
                element.style.display = 'none';
                element1.style.display = 'block';
                element2.style.display = 'none';
            }
            else {
                element.style.display = 'none';
                element1.style.display = 'none';
                element2.style.display = 'block';
            }
}

    </script>
</body>
</html>